# logs:
#   -
#     name: root
#     level: info
#     formatter: "%d%T%m%n"
#     appender:
#       -
#         type: FileLogAppender
#         file: log.txt
#       - 
#         type: StdoutLogAppender
#   -
#     name: system
#     level: debug
#     formatter: "%d%T%%n"
#     appender:
#       - 
#         type: FileLogAppender
#         path: log.txt
#       - 
#         type: StdoutLogAppender
system:
  port: 9901
  value: 12.1